Update deployments.yml

diff --git a/.github/workflows/deployments.yml b/.github/workflows/deployments.yml
--- a/.github/workflows/deployments.yml
+++ b/.github/workflows/deployments.yml
@@ -1,4 +1,5 @@
 name: Deployments example
+
 on:
   push:
     branches: [ "main", "dev" ]
@@ -6,41 +7,41 @@ on:
 jobs:
   build-and-test:
     runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v3
 
+    steps:
     - name: Checkout code
       uses: actions/checkout@v3
 
     - name: Grant execute permission for gradlew
-      run: chmod +x gradlew
+      run: chmod +x simple-go-proj/gradlew
 
     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
         java-version: '11'
         distribution: 'temurin'
-    
-    - name: Run build
+
+    - name: Run Gradle build
       uses: gradle/gradle-build-action@v2
       with:
         arguments: build
+        build-root-directory: simple-go-proj
 
     - name: Check build/libs
-      run:
-        echo "Contents of build/libs:"
-        ls -l build/libs
+      run: |
+        echo "📁 Listing contents of simple-go-proj/build/libs:"
+        ls -l simple-go-proj/build/libs || echo "Directory not found"
 
     - name: Find JAR file
       id: find_jar
       run: |
-        JAR_PATH=$(find build/libs -type f -name "*.jar" | head -n 1)
-        if [ -z "$JAR_FILE" ]; then
+        JAR_PATH=$(find simple-go-proj/build/libs -type f -name "*.jar" | head -n 1)
+        if [ -z "$JAR_PATH" ]; then
           echo "❌ JAR file not found in build/libs"
           exit 1
         fi
-        echo "JAR_PATH=$JAR_FILE" >> "$GITHUB_OUTPUT"
-    
+        echo "JAR_PATH=$JAR_PATH" >> $GITHUB_OUTPUT
+
     - name: Upload Artifact
       uses: actions/upload-artifact@v4
       with:
@@ -48,10 +49,8 @@ jobs:
         path: ${{ steps.find_jar.outputs.JAR_PATH }}
 
   deploy-dev:
-
     needs: [build-and-test]
     if: github.ref == 'refs/heads/dev'
-
     runs-on: ubuntu-latest
     environment:
       name: dev
@@ -66,10 +65,10 @@ jobs:
       - name: Check downloaded files
         run: ls -R
 
-      - name: release to dev
+      - name: Release to dev
         uses: softprops/action-gh-release@v0.1.15
         with:
-          tag_name: v$${{ vars.DEV_VERSION }}
+          tag_name: v${{ vars.DEV_VERSION }}
           token: ${{ secrets.DEV_TOKEN }}
           prerelease: true
           draft: true
@@ -77,10 +76,8 @@ jobs:
           files: greetings-deploy/*.jar
 
   deploy-prod:
-
     needs: [build-and-test]
     if: github.ref == 'refs/heads/main'
-
     runs-on: ubuntu-latest
     environment:
       name: production
@@ -94,7 +91,7 @@ jobs:
 
       - name: Check downloaded files
         run: ls -R
-        
+
       - name: GH Release
         uses: softprops/action-gh-release@v0.1.15
         with:
