Update deployments.yml

diff --git a/.github/workflows/deployments.yml b/.github/workflows/deployments.yml
--- a/.github/workflows/deployments.yml
+++ b/.github/workflows/deployments.yml
@@ -35,14 +35,11 @@ jobs:
       id: find_jar
       run: |
         JAR_PATH=$(find build/libs -type f -name "*.jar" | head -n 1)
-        echo "JAR_PATH=$JAR_PATH"
-        echo "JAR_PATH=$JAR_PATH" >> "$GITHUB_OUTPUT"
-
-    - name: Check if JAR was found
-      if: ${{ steps.find_jar.outputs.JAR_PATH == '' }}
-      run: |
-        echo "❌ JAR file not found in build/libs"
-        exit 1
+        if [ -z "$JAR_FILE" ]; then
+          echo "❌ JAR file not found in build/libs"
+          exit 1
+        fi
+        echo "JAR_PATH=$JAR_FILE" >> "$GITHUB_OUTPUT"
     
     - name: Upload Artifact
       uses: actions/upload-artifact@v4
