Update second.yml

diff --git a/.github/workflows/second.yml b/.github/workflows/second.yml
--- a/.github/workflows/second.yml
+++ b/.github/workflows/second.yml
@@ -18,3 +18,19 @@ jobs:
       - name: Execute tree
         run: |
           time tree | tee filetreelist.txt
+      
+      - name: Show OS Info
+        run: |
+          umame -a
+          cat /etc/os-release || echo "No os-release file found"
+    
+      - name: Check if tree exists
+        run: which tree || echo "tree not found"
+    
+      - name: Debug OS
+        run: |
+          if command -v lsb_release > /dev/null; then
+            lsb_release -a
+          else
+            echo "lsb_release not found"
+          fi
